### ISSUE TITLE
Multiple functions

### ISSUE THREAD

**Issue by ai** [alexlibby/postcss-filter-tint#1]
What if CSS will contain:

``` css
.foo {
    filter: tint(1, 200) blur(20px);
}
```

You should use [postcss-value-parser](https://github.com/TrySound/postcss-value-parser) for safer work with functions.
